version: "3.9"

services:
  sepal:
    build:
      context: ../..
      dockerfile: ./modules/sepal-server/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/sepal:${SEPAL_VERSION:-latest}"
    container_name: sepal
    volumes:
      - "${SEPAL_DATA_DIR}/sepal:/data"
      - "${SEPAL_DATA_DIR}/sepal/etc:/etc/sepal"
      - "${SEPAL_DATA_DIR}/user/home:/var/lib/sepal/user/home"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      HOSTING_SERVICE: "${HOSTING_SERVICE}"
      DOCKER_REGISTRY_HOST: "${DOCKER_REGISTRY_HOST}"
      SEPAL_VERSION: "${SEPAL_VERSION:-latest}"
      SEPAL_HOST: "${SEPAL_HOST}"
      SEPAL_HTTPS_PORT: "${SEPAL_HTTPS_PORT}"
      SEPAL_ADMIN_PASSWORD: "${SEPAL_ADMIN_PASSWORD}"
      SEPAL_HOST_DATA_DIR: "${SEPAL_DATA_DIR}"
      LDAP_HOST: "${LDAP_HOST}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      EE_ACCOUNT: "${EE_ACCOUNT}"
      EE_PRIVATE_KEY: "${EE_PRIVATE_KEY}"
      GOOGLE_PROJECT_ID: "${GOOGLE_PROJECT_ID}"
      GOOGLE_REGION: "${GOOGLE_REGION}"
      GOOGLE_MAPS_API_KEY: "${GOOGLE_MAPS_API_KEY}"
      NICFI_PLANET_API_KEY: "${NICFI_PLANET_API_KEY}"
    networks:
      - sepal
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/1025"
      timeout: 60s
      interval: 1s
      retries: 60
    restart: always

networks:
  sepal:
    external: true
    name: sepal
