version: "2"
services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    expose:
    - "2181"
    volumes:
    - "${WORKDIR}/zookeeper/data:/opt/zookeeper-3.4.6/data"
    environment:
      ZOOKEEPER_VERSION: "3.4.6"

  kafka:
    image: ${KAFKA_IMAGE}
    depends_on:
    - "zookeeper"
    expose:
    - "9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka_kafka_1:9092
      KAFKA_ZOOKEEPER_CONNECT: kafka_zookeeper_1:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/logs
    volumes:
    - "${WORKDIR}:/kafka"
    - "/var/run/docker.sock:/var/run/docker.sock"
    command: /bin/bash -c "sleep 5 && start-kafka.sh" # Give zookeeper a chance to initialize before starting kafka

networks:
  default:
    external:
      name: "sepal"