services:
  logger:
    networks:
      - sepal
    logging:
      driver: syslog
      options:
        cache-disabled: "true"
        syslog-address: ${SYSLOG_ADDRESS:-udp://172.20.128.2}
        tag: docker/{{.Name}}
