version: "3.9"

services:
  gee:
    build:
      context: ../..
      dockerfile: ./modules/gee/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/gee:${SEPAL_VERSION:-latest}"
    container_name: gee
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      SEPAL_ENDPOINT: "${SEPAL_ENDPOINT}"
      SEPAL_ADMIN_PASSWORD: "${SEPAL_ADMIN_PASSWORD}"
      EE_ACCOUNT: "${EE_ACCOUNT}"
      EE_PRIVATE_KEY: "${EE_PRIVATE_KEY}"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    networks:
      - sepal
    restart: always
    ulimits:
      core: 0

networks:
  sepal:
    external: true
    name: sepal
