services:
  gee:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
    volumes:  # To allow dynamic reloading in dev
      # lib/shared
      - ${SEPAL_PROJECT_DIR}/lib/js/shared/src:/usr/local/src/sepal/lib/js/shared/src
      - ${SEPAL_PROJECT_DIR}/lib/js/shared/package.json:/usr/local/src/sepal/lib/js/shared/package.json
      - ${SEPAL_PROJECT_DIR}/modules/gee/lib/shared/package-lock.json:/usr/local/src/sepal/lib/js/shared/package-lock.json
      - ${SEPAL_PROJECT_DIR}/modules/gee/lib/shared/node_modules:/usr/local/src/sepal/lib/js/shared/node_modules
      # lib/ee
      - ${SEPAL_PROJECT_DIR}/lib/js/ee/src:/usr/local/src/sepal/lib/js/ee/src
      - ${SEPAL_PROJECT_DIR}/lib/js/ee/package.json:/usr/local/src/sepal/lib/js/ee/package.json
      - ${SEPAL_PROJECT_DIR}/modules/gee/lib/ee/package-lock.json:/usr/local/src/sepal/lib/js/ee/package-lock.json
      - ${SEPAL_PROJECT_DIR}/modules/gee/lib/ee/node_modules:/usr/local/src/sepal/lib/js/ee/node_modules
      # module
      - ${SEPAL_PROJECT_DIR}/modules/gee:/usr/local/src/sepal/modules/gee
    environment:
      INSTANCES: "3"
