services:
  mysql:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
    ports: !override []

  mysql-admin:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
