services:
  backup:
    build:
      context: ../..
      dockerfile: ./modules/backup/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/backup:${SEPAL_VERSION:-latest}"
    container_name: backup
    volumes:
      - "${SEPAL_DATA_DIR}:/data"
      - "${SEPAL_BACKUP_DIR}:/backup"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      S3_BACKUP_BUCKET: "${S3_BACKUP_BUCKET}"
      BACKUP_CRON_EXP: "0 2 * * *"
    networks:
      - sepal
    restart: always

networks:
  sepal:
    external: true
    name: sepal
